### ISSUE TITLE
“是否在中国大陆” 选项设置无效

### ISSUE THREAD

**Issue by TcheL** [lyldev/yi-translate#5]
在非科学上网状态下，即使在设置中选择了“在中国大陆”，点击翻译按钮后依然长时间没有响应，经过很长很时间后最终报错 “错误：请检查您的网络连接状态。”

**Comment by lyldev** [comment]
首先谢谢你的反馈，原因应该是谷歌翻译的cn域名挂了，我会暂时尝试切换成百度翻译服务放在下个版本的更新中

**Comment by TcheL** [comment]
今天尝试看起来像是好了，可以正常翻译了，可能是不太稳定。建议在方便的位置放一个按钮，可以手动选择不同的第三方翻译服务，以便在不同的网络状态下选择合适的翻译服务。

**Comment by lyldev** [comment]
好的，会考虑你的建议的
