### ISSUE TITLE
选中文本同时按键时触发翻译面板

### ISSUE THREAD

**Issue by zhuyuuyuhz** [lyldev/yi-translate#6]
你好，我想问下，可否增加一个选中文本同时按住ctrl或者其他按键时触发翻译面板，因为很多时候，选中文本并不需要进行翻译，自己手动按键触发，可以有更好的用户体验，谢谢

**Comment by lyldev** [comment]
你好，我觉得你的需求可以通过以下设置来实现：

1.  在工具栏中点击插件进入设置面板；

2. “设置” -> “网页” -> “选中文本时的行为” -> 选择 “不显示按钮或面板”  / 或勾选 “如果不需要翻译，则不显示按钮”；

3. “快捷键” -> 查看 “翻译选中文本” 对应的快捷键，默认应该是 "Ctrl+Space"

这两步设置完后应该可以满足你的需求，如果还有什么问题请及时反馈。

谢谢。

**Comment by zhuyuuyuhz** [comment]
您好！我没有找到您说的【“设置” -> “网页” -> “选中文本时的行为” -> 选择 “不显示按钮或面板”；】选项，我的插件使用环境是win10 chrome 86.0.4240.198（正式版本） （64 位），不知道是否是环境不太一样。

**Comment by lyldev** [comment]
> 
> 
> 您好！我没有找到您说的【“设置” -> “网页” -> “选中文本时的行为” -> 选择 “不显示按钮或面板”；】选项，我的插件使用环境是win10 chrome 86.0.4240.198（正式版本） （64 位），不知道是否是环境不太一样。

我上个回答的第3步只适用于 Firefox 浏览器，而第1步、第2步在Chrome浏览器中也应该是适用的，不知你打开设置面板的方式是否正确？（参见下图）
![图片](https://user-images.githubusercontent.com/34240632/101904313-9dc42780-3bf0-11eb-8622-957280a4478d.png)

关于Chrome 浏览器中更改快捷键：

1. 在地址栏输入 chrome://extensions/shortcuts；
2. 理论上应该就可以看到快捷键的设置页面了；
3. 默认的翻译快捷键是 Ctrl+Space ，你可以试一下这个快捷键，如果不行的话可能是和其他的快捷键存在冲突，建议自行修改，如改为 Ctrl+X

**Comment by zhuyuuyuhz** [comment]
您好，感谢您的回答，已经可以设置快捷键了！谢谢

**Comment by lyldev** [comment]
OK， 不客气。
